language: node_js
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
node_js:
  - "5.0.0"
  - "4.0.0"
  - "0.12"
  - "0.11"
  - "0.10"
  - "0.8"
  - "iojs"
  - "iojs-v2"
script: "npm run-script ci-test"
services:
  - redis-server
