version: '3'
services:

  web:
    image: iromu/pool-stack:latest
    environment:
      - TCP_PORTS=8080
      - BALANCE=source
    depends_on:
      - redis
    deploy:
      mode: replicated
      replicas: 2
      restart_policy:
        condition: on-failure

  redis:
    image: redis:latest
    deploy:
      restart_policy:
        condition: on-failure

  lb:
    image: dockercloud/haproxy
    depends_on:
      - web
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      restart_policy:
        condition: on-failure
