version: '2'
services:
  app:
    build: .
    links:
      - redis:redis

  redis:
    image: redis:latest

  lb:
      image: dockercloud/haproxy
      links:
        - app
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
      ports:
        - 80:80